In [1]:
import sys

print(sys.executable)

c:\Projects\HYDRAULICS\.venv\Scripts\python.exe

In [2]:
from pathlib import Path

DATASET_PATH = Path("../dataset")

print(DATASET_PATH.exists())

True

In [3]:
files = sorted(DATASET_PATH.glob("*.txt"))

for file in files:
    print(file.name)

CE.txt
CP.txt
description.txt
documentation.txt
EPS1.txt
FS1.txt
FS2.txt
profile.txt
PS1.txt
PS2.txt
PS3.txt
PS4.txt
PS5.txt
PS6.txt
SE.txt
TS1.txt
TS2.txt
TS3.txt
TS4.txt
VS1.txt

In [4]:
import pandas as pd

fs1 = pd.read_csv(
    DATASET_PATH / "FS1.txt",
    sep="\t",
    header=None
)

In [5]:
print(type(fs1))

<class 'pandas.DataFrame'>

In [6]:
fs1.shape

(2205, 600)

In [7]:
fs1.head()

,0,1,2,3,4,5,6,7,8,9,...,590,591,592,593,594,595,596,597,598,599
0,8.990,0.770,0.641,0.006,0.000,0.000,0.001,0.003,0.001,0.001,...,7.743,7.992,7.919,7.773,7.955,7.823,7.963,7.876,7.738,8.036
1,8.919,0.815,0.709,0.009,0.004,0.000,0.001,0.000,0.000,0.001,...,7.831,8.003,7.923,7.745,7.867,7.747,7.969,7.969,7.963,7.890
2,9.179,0.683,0.528,0.008,0.003,0.001,0.003,0.003,0.004,0.006,...,7.862,7.815,7.894,7.743,7.936,7.770,7.982,7.873,7.898,7.952
3,9.034,0.728,0.595,0.009,0.001,0.004,0.003,0.003,0.003,0.001,...,7.631,7.949,7.773,8.054,7.827,8.011,7.919,7.938,7.877,7.773
4,8.729,0.705,0.446,0.014,0.007,0.003,0.001,0.003,0.001,0.000,...,7.771,7.936,7.919,7.946,7.804,7.983,7.838,7.882,7.894,7.825

In [8]:
fs1.info()

<class 'pandas.DataFrame'>
RangeIndex: 2205 entries, 0 to 2204
Columns: 600 entries, 0 to 599
dtypes: float64(600)
memory usage: 10.1 MB

In [9]:
sensor_files = [
    "PS1","PS2","PS3","PS4","PS5","PS6",
    "FS1","FS2",
    "TS1","TS2","TS3","TS4",
    "VS1",
    "CE","CP","EPS1"
]

In [10]:
sensor_data = {}

In [11]:
for sensor in sensor_files:

    df = pd.read_csv(
        DATASET_PATH / f"{sensor}.txt",
        sep="\t",
        header=None
    )

    sensor_data[sensor] = df

In [12]:
sensor_data.keys()

dict_keys(['PS1', 'PS2', 'PS3', 'PS4', 'PS5', 'PS6', 'FS1', 'FS2', 'TS1', 'TS2', 'TS3', 'TS4', 'VS1', 'CE', 'CP', 'EPS1'])

In [15]:
def inspect_sensor(sensor_name, df):

    print("=" * 50)

    print(f"Sensor : {sensor_name}")

    print(f"Shape : {df.shape}")

    print(f"Data Type : {df.dtypes.unique()}")

    print(f"Missing Values : {df.isnull().sum().sum()}")

    print("=" * 50)

In [16]:
for sensor_name, df in sensor_data.items():
    inspect_sensor(sensor_name, df)

==================================================
Sensor : PS1
Shape : (2205, 6000)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : PS2
Shape : (2205, 6000)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : PS3
Shape : (2205, 6000)
Data Type : [dtype('float64') dtype('int64')]
Missing Values : 0
==================================================
==================================================
Sensor : PS4
Shape : (2205, 6000)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : PS5
Shape : (2205, 6000)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : PS6
Shape : (2205, 6000)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : FS1
Shape : (2205, 600)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : FS2
Shape : (2205, 600)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : TS1
Shape : (2205, 60)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : TS2
Shape : (2205, 60)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : TS3
Shape : (2205, 60)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : TS4
Shape : (2205, 60)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : VS1
Shape : (2205, 60)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : CE
Shape : (2205, 60)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : CP
Shape : (2205, 60)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================
==================================================
Sensor : EPS1
Shape : (2205, 6000)
Data Type : [dtype('float64')]
Missing Values : 0
==================================================

In [17]:
sensor_data["PS3"].dtypes.value_counts()

float64    5974
int64        26
Name: count, dtype: int64

In [18]:
profile = pd.read_csv(
    DATASET_PATH / "profile.txt",
    sep="\t",
    header=None
)

In [19]:
profile.shape

(2205, 5)

In [21]:
profile.info()

<class 'pandas.DataFrame'>
RangeIndex: 2205 entries, 0 to 2204
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2205 non-null   int64
 1   1       2205 non-null   int64
 2   2       2205 non-null   int64
 3   3       2205 non-null   int64
 4   4       2205 non-null   int64
dtypes: int64(5)
memory usage: 86.3 KB

In [22]:
profile.describe()

                 0            1            2            3            4
count  2205.000000  2205.000000  2205.000000  2205.000000  2205.000000
mean     41.240816    90.693878     0.669388   107.199546     0.342857
std      42.383143    10.681802     0.817233    16.435848     0.474772
min       3.000000    73.000000     0.000000    90.000000     0.000000
25%       3.000000    80.000000     0.000000    90.000000     0.000000
50%      20.000000   100.000000     0.000000   100.000000     0.000000
75%     100.000000   100.000000     1.000000   130.000000     1.000000
max     100.000000   100.000000     2.000000   130.000000     1.000000